defaults: 

  #  _self_ refers to this file, and datasets and model refer to external configurations that are expected to be merged in. 
  # This allows Hydra to dynamically include different dataset or model configurations depending on the experiment.
  - _self_
  - datasets
  - model

data:

  # Available tasks: hallucination, inpainting
  task: hallucination

  # Available tasks: pdb, scope
  dataset: pdb

  loader:
    num_workers: 4
    prefetch_factor: 10

  sampler:
    # Setting for 48GB GPUs
    max_batch_size: 80
    max_num_res_squared: 400_000

interpolant:
  min_t: 1e-2

  twisting:
    use: False

  rots:
    corrupt: True
    sample_schedule: exp
    exp_rate: 10

  trans:
    corrupt: True
    batch_ot: True
    sample_schedule: linear
    sample_temp: 1.0
    vpsde_bmin: 0.1
    vpsde_bmax: 20.0
    potential: null
    potential_t_scaling: False
    rog:
      weight: 10.0
      cutoff: 5.0

  sampling:
    num_timesteps: 100
    do_sde: False

  self_condition: ${model.edge_features.self_condition}
  idempotency: True
  num_iterations: 1

experiment:
  debug: False
  seed: 124
  num_devices: 8
  warm_start: null
  warm_start_cfg_override: False
  training:
    mask_plddt: True
    bb_atom_scale: 0.1
    trans_scale: 0.1
    translation_loss_weight: 2.0
    t_normalize_clip: 0.9
    rotation_loss_weights: 1.0
    aux_loss_weight: 0.0
    aux_loss_use_bb_loss: True
    aux_loss_use_pair_loss: True
    aux_loss_t_pass: 0.5
  wandb:
    name: idflow_${data.dataset}_run
    project: se3-fm
  optimizer:
    lr: 0.0001
  trainer:
    overfit_batches: 0
    min_epochs: 1 # prevents early stopping
    max_epochs: 600
    accelerator: gpu
    log_every_n_steps: 1
    deterministic: False
    strategy: ddp
    check_val_every_n_epoch: 2
    accumulate_grad_batches: 1
  checkpointer:
    dirpath: ./ckpt/${experiment.wandb.project}_${data.dataset}/${experiment.wandb.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    save_top_k: -1
    every_n_epochs: 10
  # Keep this null. Will be populated at runtime.
  inference_dir: null
